apiVersion: v1
kind: Pod
metadata:
  name: docker
  labels:
    name: docker
spec:
  containers:
  - name: docker
    image: docker:latest    
    securityContext:
      privileged: true
    command: ["tail", "-f", "/dev/null"]
    resources:
      limits:
        nvidia.com/gpu: 1
  hostNetwork: true