apiVersion: v1
kind: Pod
metadata:
  name: docker
  labels:
    name: docker
spec:
  containers:
  - name: docker
    #image: ubuntu
    image: nvcr.io/nim/meta/llama3-8b-instruct:latest
    securityContext:
      privileged: true
    command: ["tail", "-f", "/dev/null"]
    resources:
      limits:
        nvidia.com/gpu: 1
  hostNetwork: true

  imagePullSecrets:
    - name: registry-secret